controller:
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    enable-brotli: "true"
    gzip-proxied: "any"
    server-tokens: "false"
  service:
    annotations:
      load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
    externalTrafficPolicy: Local
  metrics:
    enabled: true
  replicaCount: 1