apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: pg-main
  namespace: data
spec:
  instances: 1
  postgres:
    version: "15"
  pods:
    persistentVolume:
      size: "50Gi"
      storageClass: hcloud-volumes
    scheduling:
      nodeSelector:
        workload: "app"
    resources:
      requests:
        cpu: "1"
        memory: "4Gi"
      limits:
        cpu: "2"
        memory: "6Gi"
  configurations:
    sgPostgresConfig: postgres-15-generated-from-default-1.13
  prometheusAutobind: true