name: Security Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run security scan every Monday at 2 AM
    - cron: '0 2 * * 1'

jobs:
  terraform-security:
    name: Terraform Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      continue-on-error: true  # Don't fail the pipeline on security policy violations
      with:
        directory: .
        framework: terraform
        soft_fail: true  # Report issues but don't fail
        output_format: sarif
        output_file_path: checkov.sarif
        skip_check: CKV2_K8S_1,CKV2_K8S_2,CKV2_K8S_3,CKV2_K8S_4,CKV2_K8S_5,CKV_TF_1
    
    # SARIF upload is optional - requires GitHub Advanced Security
    # Commenting out to prevent pipeline failures
    # Uncomment if you have GitHub Advanced Security enabled
    # - name: Upload SARIF file
    #   uses: github/codeql-action/upload-sarif@v3
    #   if: always()
    #   with:
    #     sarif_file: checkov.sarif

  container-scan:
    name: Container Image Scanning
    runs-on: ubuntu-latest
    if: false  # Enable when you have container images to scan
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        hide-progress: false
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true  # Continue if GitHub Advanced Security is not available
      with:
        sarif_file: 'trivy-results.sarif'

  secrets-scan:
    name: Secret Detection
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        extra_args: --debug --only-verified

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run dependency check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'consigliere-dev-pack'
        path: '.'
        format: 'HTML'
        args: >
          --enableRetired
          --enableExperimental