name: Test Cluster Connection

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-connection:
    name: Test K8s Connection
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.31.0'
    
    - name: Configure and Test Kubeconfig
      env:
        KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
      run: |
        if [ -z "$KUBECONFIG_BASE64" ]; then
          echo "ERROR: KUBECONFIG_BASE64 secret is not set or empty"
          exit 1
        fi
        
        echo "Secret is present, configuring kubeconfig..."
        mkdir -p ~/.kube
        echo "$KUBECONFIG_BASE64" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config
        
        echo "Testing cluster connection..."
        kubectl get nodes
        
        echo "✓ Successfully connected to cluster!"